import Head from 'next/head'
import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import UrlConfirmButton from '../../button/UrlConfirmButton';
import { MainContainer, UrlText, InputBox, Encase, LayoutMainBox } from '../../styles/main';
import { HiddenButton } from '@/src/styles/button';
import { observer } from 'mobx-react';


function Home () {
  const router = useRouter();
  const [inputValue, setinputValue] = useState('');

  const gotoHidden = () => {
    router.push("/hidden")
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <HiddenButton onClick={gotoHidden} />
        <LayoutMainBox>
          <Encase>
            <UrlText>Free Shorten url 생성기</UrlText>
          </Encase>
          <Encase>
            <InputBox
              type='text'
              value={inputValue}
              onChange={(e) => setinputValue(e.target.value)}
            />
          </Encase>
          <UrlConfirmButton urlAddress={inputValue} />
        </LayoutMainBox>
      </MainContainer>
    </>
  );
};

export default observer(Home)